language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    update: true
    packages:
    - ffmpeg
    - shellcheck
  homebrew:
    packages:
    - ffmpeg
    update: true
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: xenial
      sudo: required
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
before_install:
  - npm install --global yarn
install:
  - yarn install
before_script:
  - cp settings/credentials.example.yaml settings/credentials.yaml
  - cp settings/configurations.example.yaml settings/configurations.yaml
script:
  - yarn test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck -x *.sh; fi
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
